const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");

const bahanBakuRoutes = require("./routes/bahanBakuRoutes");
const login = require("./routes/loginRoutes");
const menuManagement = require("./routes/menuManagement");
const detailMenuRoutes = require("./routes/detailMenuRoutes");
const pesananDetailRoutes = require("./routes/pesananDetailRoutes");
const detailPenjualanRoutes = require("./routes/detailPenjualanRoutes");
const mainPenjualanRoutes = require("./routes/mainPenjualanRoutes");
const laporanKeuanganRoutes = require("./routes/laporanKeuanganRoutes");
const historyRoutes = require("./routes/historyRoutes");

/* =========================
   MONGODB CONFIG & MODELS
========================= */
const { connectMongoDB } = require("./config/sequelize");
const {
  Pegawai,
  BahanBaku,
  Menu,
  DetailMenu,
  Pembelian,
  HeaderPenjualan,
  Penjualan,
  Pesanan,
  PesananDetail,
} = require("./models/index");

/* =========================
   EXPRESS SETUP
========================= */
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

/* =========================
   CLEAR DATABASE
========================= */
const clearDatabase = async () => {
  await Promise.all([
    Pegawai.deleteMany({}),
    BahanBaku.deleteMany({}),
    Menu.deleteMany({}),
    DetailMenu.deleteMany({}),
    Pembelian.deleteMany({}),
    HeaderPenjualan.deleteMany({}),
    Penjualan.deleteMany({}),
    Pesanan.deleteMany({}),
    PesananDetail.deleteMany({}),
  ]);
};

/* =========================
   SEED DATABASE (FROM MYSQL)
========================= */
const seedDatabase = async () => {
  console.log("🌱 Seeding MongoDB from MySQL data...");

  await clearDatabase();

  /* ===== PEGAWAI ===== */
  await Pegawai.insertMany([
    {
      pegawai_id: 1,
      pegawai_nama: "Budi",
      pegawai_email: "b@b.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 2,
      pegawai_nama: "Siti",
      pegawai_email: "siti@warungbulis.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 3,
      pegawai_nama: "Andi",
      pegawai_email: "andi@warungbulis.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 4,
      pegawai_nama: "Rina",
      pegawai_email: "rina@warungbulis.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 5,
      pegawai_nama: "Dewi",
      pegawai_email: "dewi@warungbulis.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 6,
      pegawai_nama: "Agus",
      pegawai_email: "agus@warungbulis.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 7,
      pegawai_nama: "Tina",
      pegawai_email: "tina@warungbulis.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 8,
      pegawai_nama: "Eko",
      pegawai_email: "eko@warungbulis.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 9,
      pegawai_nama: "Lina",
      pegawai_email: "lina@warungbulis.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 10,
      pegawai_nama: "Rudi",
      pegawai_email: "rudi@warungbulis.com",
      pegawai_password:
        "$2b$10$vd.ZdRs2h9mqGJyoiGx1oOuVJkHn/FglS.DB4uO.6Wa1kkIyO2/lS",
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pegawai_id: 11,
      pegawai_nama: "Mikael",
      pegawai_email: "mikael@warungbulis.com",
      pegawai_password:
        "$2a$12$rhjOvfoFm3jMN9KCW9FqeORO2JjWEiFNIOBlWFJfqivv8wNc5Smym",
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
  ]);

  /* ===== BAHAN BAKU ===== */
  await BahanBaku.insertMany([
    {
      bahan_baku_id: 1,
      bahan_baku_nama: "Bandeng",
      bahan_baku_jumlah: 25,
      bahan_baku_harga: 425000,
      bahan_baku_satuan: "unit",
      bahan_baku_harga_satuan: 17000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 2,
      bahan_baku_nama: "Cabe Merah",
      bahan_baku_jumlah: 3,
      bahan_baku_harga: 54000,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 18000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 3,
      bahan_baku_nama: "Bawang Putih",
      bahan_baku_jumlah: 4.2,
      bahan_baku_harga: 126000,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 30000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 4,
      bahan_baku_nama: "Bawang Merah",
      bahan_baku_jumlah: 3.18,
      bahan_baku_harga: 82680,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 26000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 5,
      bahan_baku_nama: "Biji Kemiri",
      bahan_baku_jumlah: 1.245,
      bahan_baku_harga: 59760,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 48000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 6,
      bahan_baku_nama: "Ketumbar",
      bahan_baku_jumlah: 1.11,
      bahan_baku_harga: 52170,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 47000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 7,
      bahan_baku_nama: "Jahe",
      bahan_baku_jumlah: 1.72,
      bahan_baku_harga: 41280,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 24000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 8,
      bahan_baku_nama: "Kecap Manis",
      bahan_baku_jumlah: 3,
      bahan_baku_harga: 111000,
      bahan_baku_satuan: "liter",
      bahan_baku_harga_satuan: 37000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 9,
      bahan_baku_nama: "Garam",
      bahan_baku_jumlah: 0.45,
      bahan_baku_harga: 72000,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 16000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 10,
      bahan_baku_nama: "Minyak Goreng",
      bahan_baku_jumlah: 2,
      bahan_baku_harga: 37000,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 18500,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 11,
      bahan_baku_nama: "Tepung Terigu",
      bahan_baku_jumlah: 4,
      bahan_baku_harga: 41000,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 10250,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 12,
      bahan_baku_nama: "Tepung Biang",
      bahan_baku_jumlah: 3,
      bahan_baku_harga: 31500,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 10500,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 13,
      bahan_baku_nama: "Telur",
      bahan_baku_jumlah: 50,
      bahan_baku_harga: 128000,
      bahan_baku_satuan: "unit",
      bahan_baku_harga_satuan: 2560,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 14,
      bahan_baku_nama: "Cabe Rawit",
      bahan_baku_jumlah: 2.5,
      bahan_baku_harga: 50000,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 20000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 15,
      bahan_baku_nama: "Daun Jeruk",
      bahan_baku_jumlah: 0.05,
      bahan_baku_harga: 1750,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 35000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 16,
      bahan_baku_nama: "Sachet Santan",
      bahan_baku_jumlah: 30,
      bahan_baku_harga: 60000,
      bahan_baku_satuan: "unit",
      bahan_baku_harga_satuan: 2000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 17,
      bahan_baku_nama: "Merica",
      bahan_baku_jumlah: 0.1,
      bahan_baku_harga: 10000,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 100000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 18,
      bahan_baku_nama: "Gula",
      bahan_baku_jumlah: 1.92,
      bahan_baku_harga: 30720,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 16000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 19,
      bahan_baku_nama: "Daun Pisang",
      bahan_baku_jumlah: 100,
      bahan_baku_harga: 50000,
      bahan_baku_satuan: "unit",
      bahan_baku_harga_satuan: 500,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 20,
      bahan_baku_nama: "Cincau",
      bahan_baku_jumlah: 2.34,
      bahan_baku_harga: 50000,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 46800,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 21,
      bahan_baku_nama: "Susu Kental",
      bahan_baku_jumlah: 2.02,
      bahan_baku_harga: 70700,
      bahan_baku_satuan: "liter",
      bahan_baku_harga_satuan: 35000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 22,
      bahan_baku_nama: "Nata De Coco",
      bahan_baku_jumlah: 2.67,
      bahan_baku_harga: 48060,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 18000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 23,
      bahan_baku_nama: "Sachet Teh",
      bahan_baku_jumlah: 150,
      bahan_baku_harga: 120000,
      bahan_baku_satuan: "unit",
      bahan_baku_harga_satuan: 800,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      bahan_baku_id: 24,
      bahan_baku_nama: "Kaldu Bubuk",
      bahan_baku_jumlah: 1,
      bahan_baku_harga: 30000,
      bahan_baku_satuan: "kg",
      bahan_baku_harga_satuan: 30000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
  ]);

  /* ===== MENU ===== */
  await Menu.insertMany([
    {
      menu_id: 1,
      menu_nama: "Bandeng Bakar",
      menu_harga: 60000,
      menu_gambar: "https://i.imgur.com/9UFXrw5.jpeg",
      menu_status_aktif: 1,
      createdAt: "10/19/2025",
      updatedAt: "11/06/2025",
    },
    {
      menu_id: 2,
      menu_nama: "Bandeng Goreng",
      menu_harga: 60000,
      menu_gambar: "https://i.imgur.com/EXpwRPU.jpeg",
      menu_status_aktif: 1,
      createdAt: "10/19/2025",
      updatedAt: "11/13/2025",
    },
    {
      menu_id: 3,
      menu_nama: "Bandeng Goreng Crispy ",
      menu_harga: 60000,
      menu_gambar: " https://i.imgur.com/z7bMwBS.jpeg",
      menu_status_aktif: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      menu_id: 4,
      menu_nama: "Otak Otak Bandeng",
      menu_harga: 70000,
      menu_gambar: "https://i.imgur.com/t7i8K4M.jpeg",
      menu_status_aktif: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      menu_id: 5,
      menu_nama: "Bandeng Pepes",
      menu_harga: 70000,
      menu_gambar: " https://i.imgur.com/PPYYNRa.jpeg",
      menu_status_aktif: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      menu_id: 6,
      menu_nama: "Es Cincau Susu",
      menu_harga: 7000,
      menu_gambar: "https://i.imgur.com/wQo8yqD.jpeg",
      menu_status_aktif: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      menu_id: 7,
      menu_nama: "Es Teh",
      menu_harga: 4000,
      menu_gambar:
        "https://th.bing.com/th/id/OIP.rCtqYWrKKpktfUZqLxj4pAHaHa?w=216&h=215&c=7&r=0&o=7&cb=ucfimg2&dpr=1.3&pid=1.7&rm=3&ucfimg=1",
      menu_status_aktif: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      menu_id: 8,
      menu_nama: "Pecel Lele",
      menu_harga: 24000,
      menu_gambar:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbpIoXzpb43E0WJOwOfvtJPtyMgJaX3ai5QA&s",
      menu_status_aktif: 0,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      menu_id: 9,
      menu_nama: "Bakso",
      menu_harga: 20000,
      menu_gambar:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSikceAHEyId9rMz8X8CI1Md2U1gsdxKZBm_Q&s",
      menu_status_aktif: 0,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      menu_id: 10,
      menu_nama: "Rawon",
      menu_harga: 28000,
      menu_gambar:
        "https://awsimages.detik.net.id/community/media/visual/2023/03/14/resep-rawon-daging-surabaya_169.jpeg?w=600&q=90",
      menu_status_aktif: 0,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      menu_id: 11,
      menu_nama: "Tahu Goreng",
      menu_harga: 3,
      menu_gambar:
        "https://th.bing.com/th/id/OSK.ecf9df001af81740b902293078ed5c67?w=200&h=126&c=7&rs=1&qlt=80&r=0&o=6&cdv=1&cb=ucfimg1&dpr=1.3&pid=16.1&ucfimg=1",
      menu_status_aktif: 0,
      createdAt: "11/13/2025",
      updatedAt: "11/14/2025",
    },
  ]);

  await DetailMenu.insertMany([
    {
      detail_menu_id: 1,
      detail_menu_nama_bahan: "Bandeng",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 17000,
      menu_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 2,
      detail_menu_nama_bahan: "Cabe Merah",
      detail_menu_jumlah: 0.011,
      detail_menu_satuan: "kg",
      detail_menu_harga: 220,
      menu_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 3,
      detail_menu_nama_bahan: "Bawang Putih",
      detail_menu_jumlah: 0.015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 450,
      menu_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 4,
      detail_menu_nama_bahan: "Bawang Merah",
      detail_menu_jumlah: 0.015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 390,
      menu_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 5,
      detail_menu_nama_bahan: "Biji Kemiri",
      detail_menu_jumlah: 0.015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 720,
      menu_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 6,
      detail_menu_nama_bahan: "Ketumbar",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 235,
      menu_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 7,
      detail_menu_nama_bahan: "Jahe",
      detail_menu_jumlah: 0.03,
      detail_menu_satuan: "kg",
      detail_menu_harga: 720,
      menu_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 8,
      detail_menu_nama_bahan: "Kecap Manis",
      detail_menu_jumlah: 0.045,
      detail_menu_satuan: "liter",
      detail_menu_harga: 1665,
      menu_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 9,
      detail_menu_nama_bahan: "Bandeng",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 17000,
      menu_id: 2,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 10,
      detail_menu_nama_bahan: "Bawang Putih",
      detail_menu_jumlah: 0.003,
      detail_menu_satuan: "kg",
      detail_menu_harga: 90,
      menu_id: 2,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 11,
      detail_menu_nama_bahan: "Garam",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 80,
      menu_id: 2,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 12,
      detail_menu_nama_bahan: "Kaldu Bubuk",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 150,
      menu_id: 2,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 13,
      detail_menu_nama_bahan: "Minyak Goreng",
      detail_menu_jumlah: 0.25,
      detail_menu_satuan: "liter",
      detail_menu_harga: 4625,
      menu_id: 2,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 14,
      detail_menu_nama_bahan: "Bandeng",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 17000,
      menu_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 15,
      detail_menu_nama_bahan: "Bawang Putih",
      detail_menu_jumlah: 0.003,
      detail_menu_satuan: "kg",
      detail_menu_harga: 90,
      menu_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 16,
      detail_menu_nama_bahan: "Ketumbar",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 235,
      menu_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 17,
      detail_menu_nama_bahan: "Garam",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 80,
      menu_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 18,
      detail_menu_nama_bahan: "Kaldu Bubuk",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 150,
      menu_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 19,
      detail_menu_nama_bahan: "Tepung Biang",
      detail_menu_jumlah: 0.075,
      detail_menu_satuan: "kg",
      detail_menu_harga: 787.5,
      menu_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 20,
      detail_menu_nama_bahan: "Tepung Terigu",
      detail_menu_jumlah: 0.075,
      detail_menu_satuan: "kg",
      detail_menu_harga: 768.75,
      menu_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 21,
      detail_menu_nama_bahan: "Telur",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 2560,
      menu_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 22,
      detail_menu_nama_bahan: "Minyak Goreng",
      detail_menu_jumlah: 0.25,
      detail_menu_satuan: "liter",
      detail_menu_harga: 4625,
      menu_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 23,
      detail_menu_nama_bahan: "Bandeng",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 17000,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 24,
      detail_menu_nama_bahan: "Bawang Merah",
      detail_menu_jumlah: 0.03,
      detail_menu_satuan: "kg",
      detail_menu_harga: 780,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 25,
      detail_menu_nama_bahan: "Bawang Putih",
      detail_menu_jumlah: 0.003,
      detail_menu_satuan: "kg",
      detail_menu_harga: 90,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 26,
      detail_menu_nama_bahan: "Cabe Merah",
      detail_menu_jumlah: 0.077,
      detail_menu_satuan: "kg",
      detail_menu_harga: 1540,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 27,
      detail_menu_nama_bahan: "Cabe Rawit",
      detail_menu_jumlah: 0.0015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 270,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 28,
      detail_menu_nama_bahan: "Jahe",
      detail_menu_jumlah: 0.03,
      detail_menu_satuan: "kg",
      detail_menu_harga: 720,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 29,
      detail_menu_nama_bahan: "Ketumbar",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 235,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 30,
      detail_menu_nama_bahan: "Daun Jeruk",
      detail_menu_jumlah: 0.0002,
      detail_menu_satuan: "kg",
      detail_menu_harga: 7,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 31,
      detail_menu_nama_bahan: "Biji Kemiri",
      detail_menu_jumlah: 0.015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 720,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 32,
      detail_menu_nama_bahan: "Ketumbar",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 235,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 33,
      detail_menu_nama_bahan: "Merica",
      detail_menu_jumlah: 0.0025,
      detail_menu_satuan: "kg",
      detail_menu_harga: 250,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 34,
      detail_menu_nama_bahan: "Telur",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 2560,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 35,
      detail_menu_nama_bahan: "Sachet Santan",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 2000,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 36,
      detail_menu_nama_bahan: "Garam",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 80,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 37,
      detail_menu_nama_bahan: "Gula",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 80,
      menu_id: 4,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 38,
      detail_menu_nama_bahan: "Bandeng",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 17000,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 39,
      detail_menu_nama_bahan: "Bawang Merah",
      detail_menu_jumlah: 0.03,
      detail_menu_satuan: "kg",
      detail_menu_harga: 780,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 40,
      detail_menu_nama_bahan: "Bawang Putih",
      detail_menu_jumlah: 0.003,
      detail_menu_satuan: "kg",
      detail_menu_harga: 90,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 41,
      detail_menu_nama_bahan: "Cabe Merah",
      detail_menu_jumlah: 0.077,
      detail_menu_satuan: "kg",
      detail_menu_harga: 1540,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 42,
      detail_menu_nama_bahan: "Cabe Rawit",
      detail_menu_jumlah: 0.0015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 270,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 43,
      detail_menu_nama_bahan: "Jahe",
      detail_menu_jumlah: 0.03,
      detail_menu_satuan: "kg",
      detail_menu_harga: 720,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 44,
      detail_menu_nama_bahan: "Biji Kemiri",
      detail_menu_jumlah: 0.015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 720,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 45,
      detail_menu_nama_bahan: "Ketumbar",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 235,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 46,
      detail_menu_nama_bahan: "Garam",
      detail_menu_jumlah: 0.0025,
      detail_menu_satuan: "kg",
      detail_menu_harga: 40,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 47,
      detail_menu_nama_bahan: "Gula",
      detail_menu_jumlah: 0.005,
      detail_menu_satuan: "kg",
      detail_menu_harga: 80,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 48,
      detail_menu_nama_bahan: "Kaldu Bubuk",
      detail_menu_jumlah: 0.0025,
      detail_menu_satuan: "kg",
      detail_menu_harga: 75,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 49,
      detail_menu_nama_bahan: "Daun Pisang",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 500,
      menu_id: 5,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 50,
      detail_menu_nama_bahan: "Cincau",
      detail_menu_jumlah: 0.045,
      detail_menu_satuan: "kg",
      detail_menu_harga: 2106,
      menu_id: 6,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 51,
      detail_menu_nama_bahan: "Gula",
      detail_menu_jumlah: 0.015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 240,
      menu_id: 6,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 52,
      detail_menu_nama_bahan: "Susu Kental",
      detail_menu_jumlah: 0.015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 525,
      menu_id: 6,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 53,
      detail_menu_nama_bahan: "Nata De Coco",
      detail_menu_jumlah: 0.015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 721,
      menu_id: 6,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 54,
      detail_menu_nama_bahan: "Sachet Teh",
      detail_menu_jumlah: 1,
      detail_menu_satuan: "unit",
      detail_menu_harga: 800,
      menu_id: 7,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      detail_menu_id: 55,
      detail_menu_nama_bahan: "Gula",
      detail_menu_jumlah: 0.015,
      detail_menu_satuan: "kg",
      detail_menu_harga: 240,
      menu_id: 7,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
  ]);

  await Pembelian.insertMany([
    {
      pembelian_id: 1,
      bahan_baku_id: 1,
      pembelian_jumlah: 10,
      pembelian_satuan: "unit",
      pembelian_harga_satuan: 17000,
      createdAt: "11/07/2025",
      updatedAt: "11/07/2025",
    },
    {
      pembelian_id: 2,
      bahan_baku_id: 2,
      pembelian_jumlah: 1,
      pembelian_satuan: "kg",
      pembelian_harga_satuan: 54000,
      createdAt: "11/06/2025",
      updatedAt: "11/06/2025",
    },
    {
      pembelian_id: 3,
      bahan_baku_id: 3,
      pembelian_jumlah: 0.5,
      pembelian_satuan: "kg",
      pembelian_harga_satuan: 126000,
      createdAt: "11/06/2025",
      updatedAt: "11/06/2025",
    },
    {
      pembelian_id: 4,
      bahan_baku_id: 4,
      pembelian_jumlah: 0.5,
      pembelian_satuan: "kg",
      pembelian_harga_satuan: 82680,
      createdAt: "11/06/2025",
      updatedAt: "11/06/2025",
    },
    {
      pembelian_id: 5,
      bahan_baku_id: 5,
      pembelian_jumlah: 0.2,
      pembelian_satuan: "kg",
      pembelian_harga_satuan: 59760,
      createdAt: "11/06/2025",
      updatedAt: "11/06/2025",
    },
    {
      pembelian_id: 6,
      bahan_baku_id: 6,
      pembelian_jumlah: 0.2,
      pembelian_satuan: "kg",
      pembelian_harga_satuan: 47000,
      createdAt: "11/06/2025",
      updatedAt: "11/06/2025",
    },
    {
      pembelian_id: 7,
      bahan_baku_id: 7,
      pembelian_jumlah: 0.3,
      pembelian_satuan: "kg",
      pembelian_harga_satuan: 24000,
      createdAt: "11/06/2025",
      updatedAt: "11/06/2025",
    },
    {
      pembelian_id: 8,
      bahan_baku_id: 8,
      pembelian_jumlah: 2,
      pembelian_satuan: "liter",
      pembelian_harga_satuan: 111000,
      createdAt: "11/06/2025",
      updatedAt: "11/06/2025",
    },
    {
      pembelian_id: 9,
      bahan_baku_id: 9,
      pembelian_jumlah: 3,
      pembelian_satuan: "kg",
      pembelian_harga_satuan: 16000,
      createdAt: "11/06/2025",
      updatedAt: "11/06/2025",
    },
    {
      pembelian_id: 10,
      bahan_baku_id: 10,
      pembelian_jumlah: 2,
      pembelian_satuan: "kg",
      pembelian_harga_satuan: 18500,
      createdAt: "11/06/2025",
      updatedAt: "11/06/2025",
    },
  ]);

  await HeaderPenjualan.insertMany([
    {
      header_penjualan_id: 1,
      header_penjualan_tanggal: "10/01/2025",
      header_penjualan_jenis: "offline",
      header_penjualan_keterangan:
        "Penjualan menu offline, 2 Bandeng Bakar dan 3 Es Cincau Susu",
      header_penjualan_biaya_tambahan: 5000,
      header_penjualan_uang_muka: 0,
      pegawai_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      header_penjualan_id: 2,
      header_penjualan_tanggal: "11/01/2025",
      header_penjualan_jenis: "online",
      header_penjualan_keterangan:
        "Penjualan menu online, 1 Bandeng Goreng dan 2 Es Teh",
      header_penjualan_biaya_tambahan: 10000,
      header_penjualan_uang_muka: 50,
      pegawai_id: 2,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      header_penjualan_id: 3,
      header_penjualan_tanggal: "10/02/2025",
      header_penjualan_jenis: "offline",
      header_penjualan_keterangan:
        "Penjualan menu offline, 1 Bandeng Goreng Crispy",
      header_penjualan_biaya_tambahan: 3000,
      header_penjualan_uang_muka: 0,
      pegawai_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      header_penjualan_id: 4,
      header_penjualan_tanggal: "10/02/2025",
      header_penjualan_jenis: "online",
      header_penjualan_keterangan: "Penjualan menu online, 2 Otak Otak Bandeng",
      header_penjualan_biaya_tambahan: 7000,
      header_penjualan_uang_muka: 20,
      pegawai_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      header_penjualan_id: 5,
      header_penjualan_tanggal: "10/03/2025",
      header_penjualan_jenis: "offline",
      header_penjualan_keterangan: "Penjualan menu offline, 1 Bandeng Pepes",
      header_penjualan_biaya_tambahan: 4000,
      header_penjualan_uang_muka: 0,
      pegawai_id: 2,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      header_penjualan_id: 6,
      header_penjualan_tanggal: "10/03/2025",
      header_penjualan_jenis: "online",
      header_penjualan_keterangan: "Penjualan menu online, 2 Es Cincau Susu",
      header_penjualan_biaya_tambahan: 6000,
      header_penjualan_uang_muka: 10,
      pegawai_id: 3,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      header_penjualan_id: 7,
      header_penjualan_tanggal: "10/04/2025",
      header_penjualan_jenis: "offline",
      header_penjualan_keterangan: "Penjualan menu offline, 3 Bandeng Bakar",
      header_penjualan_biaya_tambahan: 4000,
      header_penjualan_uang_muka: 0,
      pegawai_id: 1,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      header_penjualan_id: 8,
      header_penjualan_tanggal: "10/04/2025",
      header_penjualan_jenis: "online",
      header_penjualan_keterangan:
        "Penjualan menu online, 1 Bandeng Pepes dan 2 Es Teh",
      header_penjualan_biaya_tambahan: 5000,
      header_penjualan_uang_muka: 15,
      pegawai_id: 2,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
  ]);

  await Penjualan.insertMany([
    {
      penjualan_id: 1,
      header_penjualan_id: 1,
      menu_id: 1,
      penjualan_jumlah: 2,
      subtotal: 120000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 2,
      header_penjualan_id: 1,
      menu_id: 6,
      penjualan_jumlah: 3,
      subtotal: 21000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 3,
      header_penjualan_id: 2,
      menu_id: 2,
      penjualan_jumlah: 1,
      subtotal: 60000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 4,
      header_penjualan_id: 2,
      menu_id: 7,
      penjualan_jumlah: 2,
      subtotal: 8000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 5,
      header_penjualan_id: 3,
      menu_id: 3,
      penjualan_jumlah: 1,
      subtotal: 60000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 6,
      header_penjualan_id: 4,
      menu_id: 4,
      penjualan_jumlah: 2,
      subtotal: 140000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 7,
      header_penjualan_id: 5,
      menu_id: 5,
      penjualan_jumlah: 1,
      subtotal: 70000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 8,
      header_penjualan_id: 6,
      menu_id: 6,
      penjualan_jumlah: 2,
      subtotal: 14000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 9,
      header_penjualan_id: 7,
      menu_id: 1,
      penjualan_jumlah: 3,
      subtotal: 180000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 10,
      header_penjualan_id: 8,
      menu_id: 5,
      penjualan_jumlah: 1,
      subtotal: 70000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      penjualan_id: 11,
      header_penjualan_id: 8,
      menu_id: 7,
      penjualan_jumlah: 2,
      subtotal: 8000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
  ]);

  await Pesanan.insertMany([
    {
      pesanan_id: 1,
      pesanan_nama: "Ali",
      pesanan_lokasi: "Jln. Mawar No. 12, Surabaya",
      pesanan_email: "ali@email.com",
      pesanan_status: "pending",
      nomer_telpon: "08120093101",
      pesanan_tanggal: "10/01/2025",
      pesanan_tanggal_pengiriman: "11/01/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
    {
      pesanan_id: 2,
      pesanan_nama: "Ali",
      pesanan_lokasi: "Jln. Melati No. 5, Gresik",
      pesanan_email: "ali@email.com",
      pesanan_status: "diproses",
      nomer_telpon: "08120007302",
      pesanan_tanggal: "10/01/2025",
      pesanan_tanggal_pengiriman: "11/01/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
    {
      pesanan_id: 3,
      pesanan_nama: "Ali",
      pesanan_lokasi: "Jln. Kenanga No. 8, Sidoarjo",
      pesanan_email: "ali@email.com",
      pesanan_status: "terkirim",
      nomer_telpon: "08120112303",
      pesanan_tanggal: "10/02/2025",
      pesanan_tanggal_pengiriman: "11/02/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
    {
      pesanan_id: 4,
      pesanan_nama: "Tari",
      pesanan_lokasi: "Jln. Dahlia No. 3, Malang",
      pesanan_email: "tari@email.com",
      pesanan_status: "pending",
      nomer_telpon: "08128765004",
      pesanan_tanggal: "10/02/2025",
      pesanan_tanggal_pengiriman: "11/02/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
    {
      pesanan_id: 5,
      pesanan_nama: "Bayu",
      pesanan_lokasi: "Jln. Anggrek No. 9, Lamongan",
      pesanan_email: "bayu@email.com",
      pesanan_status: "pending",
      nomer_telpon: "08120238965",
      pesanan_tanggal: "10/03/2025",
      pesanan_tanggal_pengiriman: "11/03/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
    {
      pesanan_id: 6,
      pesanan_nama: "Nina",
      pesanan_lokasi: "Jln. Teratai No. 7, Kediri",
      pesanan_email: "nina@email.com",
      pesanan_status: "pending",
      nomer_telpon: "08120019966",
      pesanan_tanggal: "10/03/2025",
      pesanan_tanggal_pengiriman: "12/03/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
    {
      pesanan_id: 7,
      pesanan_nama: "Fajar",
      pesanan_lokasi: "Jln. Flamboyan No. 4, Blitar",
      pesanan_email: "fajar@email.com",
      pesanan_status: "pending",
      nomer_telpon: "08126589107",
      pesanan_tanggal: "10/04/2025",
      pesanan_tanggal_pengiriman: "12/04/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
    {
      pesanan_id: 8,
      pesanan_nama: "Lia",
      pesanan_lokasi: "Jln. Cempaka No. 6, Tulungagung",
      pesanan_email: "lia@email.com",
      pesanan_status: "pending",
      nomer_telpon: "08120449308",
      pesanan_tanggal: "10/04/2025",
      pesanan_tanggal_pengiriman: "12/04/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
    {
      pesanan_id: 9,
      pesanan_nama: "Riski",
      pesanan_lokasi: "Jln. Bougenville No. 10, Madiun",
      pesanan_email: "riski@email.com",
      pesanan_status: "pending",
      nomer_telpon: "08120002309",
      pesanan_tanggal: "10/05/2025",
      pesanan_tanggal_pengiriman: "12/05/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
    {
      pesanan_id: 10,
      pesanan_nama: "Salsa",
      pesanan_lokasi: "Jln. Kamboja No. 2, Jombang",
      pesanan_email: "salsa@email.com",
      pesanan_status: "pending",
      nomer_telpon: "08120643010",
      pesanan_tanggal: "10/05/2025",
      pesanan_tanggal_pengiriman: "12/05/2025",
      createdAt: "10/19/2025",
      updatedAt: "12/03/2025",
    },
  ]);

  await PesananDetail.insertMany([
    {
      pesanan_detail_id: 1,
      menu_id: 1,
      pesanan_detail_jumlah: 2,
      pesanan_id: 1,
      subtotal: 120000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 2,
      menu_id: 6,
      pesanan_detail_jumlah: 1,
      pesanan_id: 1,
      subtotal: 7000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 3,
      menu_id: 2,
      pesanan_detail_jumlah: 1,
      pesanan_id: 2,
      subtotal: 60000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 4,
      menu_id: 7,
      pesanan_detail_jumlah: 2,
      pesanan_id: 2,
      subtotal: 8000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 5,
      menu_id: 3,
      pesanan_detail_jumlah: 1,
      pesanan_id: 3,
      subtotal: 60000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 6,
      menu_id: 4,
      pesanan_detail_jumlah: 2,
      pesanan_id: 3,
      subtotal: 140000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 7,
      menu_id: 5,
      pesanan_detail_jumlah: 1,
      pesanan_id: 4,
      subtotal: 70000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 8,
      menu_id: 6,
      pesanan_detail_jumlah: 2,
      pesanan_id: 4,
      subtotal: 14000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 9,
      menu_id: 1,
      pesanan_detail_jumlah: 3,
      pesanan_id: 5,
      subtotal: 180000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 10,
      menu_id: 7,
      pesanan_detail_jumlah: 1,
      pesanan_id: 5,
      subtotal: 4000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 11,
      menu_id: 2,
      pesanan_detail_jumlah: 1,
      pesanan_id: 6,
      subtotal: 60000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 12,
      menu_id: 4,
      pesanan_detail_jumlah: 1,
      pesanan_id: 6,
      subtotal: 70000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 13,
      menu_id: 1,
      pesanan_detail_jumlah: 2,
      pesanan_id: 7,
      subtotal: 120000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 14,
      menu_id: 6,
      pesanan_detail_jumlah: 1,
      pesanan_id: 7,
      subtotal: 7000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 15,
      menu_id: 3,
      pesanan_detail_jumlah: 2,
      pesanan_id: 8,
      subtotal: 120000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 16,
      menu_id: 5,
      pesanan_detail_jumlah: 1,
      pesanan_id: 8,
      subtotal: 70000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 17,
      menu_id: 2,
      pesanan_detail_jumlah: 2,
      pesanan_id: 9,
      subtotal: 120000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 18,
      menu_id: 7,
      pesanan_detail_jumlah: 1,
      pesanan_id: 9,
      subtotal: 4000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 19,
      menu_id: 4,
      pesanan_detail_jumlah: 2,
      pesanan_id: 10,
      subtotal: 140000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
    {
      pesanan_detail_id: 20,
      menu_id: 6,
      pesanan_detail_jumlah: 1,
      pesanan_id: 10,
      subtotal: 7000,
      createdAt: "10/19/2025",
      updatedAt: "10/19/2025",
    },
  ]);

  console.log("✅ Seeder selesai & database konsisten");
};

/* =========================
   AUTO INIT DATABASE
========================= */
const initDatabase = async () => {
  const menuCount = await Menu.countDocuments();
  if (menuCount === 0) {
    console.log("📦 Database kosong → jalankan seeder");
    await seedDatabase();
  } else {
    console.log("✅ Database sudah terisi → skip seeder");
  }
};

// login
app.use("/api/login", login);

// menu management
app.use("/api/menu_management", menuManagement);

// menu detail
app.use("/api/menu_management/detail", detailMenuRoutes);

// bahan baku
app.use("/api/bahan_Baku", bahanBakuRoutes);

// pesanan detail
app.use("/api/pesanan_detail/detail", pesananDetailRoutes);

// detail penjualan
app.use("/api/detail_penjualan", detailPenjualanRoutes);

//history
app.use("/api/history/", historyRoutes);
// ====================================================================

// main penjualan
app.use("/api/main_penjualan", mainPenjualanRoutes);

// laporan keuangan
app.use("/api/laporan_keuangan", laporanKeuanganRoutes);

/* =========================
   SERVER START
========================= */
const PORT = 3000;

app.listen(PORT, async () => {
  try {
    await connectMongoDB();
    console.log("✅ MongoDB connected");

    await initDatabase();

    console.log(`🚀 Server running on port ${PORT}`);
  } catch (err) {
    console.error("❌ Startup error:", err);
  }
});
